config/routes.rb
LaurenFlynn::Application.routes.draw do

  resources :users

  root to: 'users#home'

  get '/light_exp', to: 'static_pages#light_exp'
  get '/light_wall', to: 'static_pages#light_wall'
  get '/carvings', to: 'static_pages#carvings'
  get '/sisters', to: 'static_pages#sisters'
  get '/lines', to: 'static_pages#lines'
  get '/figures', to: 'static_pages#figures'
  get '/newer', to: 'static_pages#newer'
  get '/new', to: 'static_pages#new'
  get '/text', to: 'static_pages#text'
  get '/cv', to: 'static_pages#cv'
  get '/contact', to: 'static_pages#contact'

  resources :users

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def light_exp
  end

  def light_wall
  end

  def carvings
  end

  def sisters
  end

  def lines
  end

  def figures
  end

  def newer
  end

  def new
  end

  def text
  end

  def cv
  end

  def contact
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>a chike t. abuah production</p>
  </small>
  <nav>
  </nav>
</footer>

app/views/layouts/_sidebar.html.erb
<div class="span2">
    <ul id="sidenav" class="nav nav-pills nav-stacked">

    <%= link_to "lauren flynn", root_path, id: "logo" %>
    <br>
      <h5> works: </h5>
      <li class="<%= 'active' if current_page?(light_exp_path) %>"> <%= link_to "light experiments", light_exp_path %></li>
      <li class="<%= 'active' if current_page?(light_wall_path) %>"><%= link_to "traversing lights", light_wall_path %></li>
      <li class="<%= 'active' if current_page?(carvings_path) %>"><%= link_to "carvings", carvings_path %></li>
      <li class="<%= 'active' if current_page?(sisters_path) %>"><%= link_to "sisters", sisters_path %></li>
      <li class="<%= 'active' if current_page?(lines_path) %>"><%= link_to "lines", lines_path %></li>
      <li class="<%= 'active' if current_page?(figures_path) %>"><%= link_to "figures", figures_path %></li>
      <li class="<%= 'active' if current_page?(newer_path) %>"><%= link_to "newer embroideries", newer_path %></li>
      <li class="<%= 'active' if current_page?(new_path) %>"><%= link_to "new embroideries", new_path %></li>
      <br>
      <h5> info: </h5>
      <li class="<%= 'active' if current_page?(text_path) %>"><%= link_to "text", text_path %></li>
      <li class="<%= 'active' if current_page?(cv_path) %>"><%= link_to "cv", cv_path %></li>
      <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "contact", contact_path %></li>

    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LaurenFlynn</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/sidebar' %>
<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/static_pages/carvings.html.erb
<div class="wrapper">
	<%= link_to image_tag("grimfuture.jpg", alt: "grim dark future"), 'http://en.wikipedia.org/wiki/Grinnell,_Iowa' %>
	<%= link_to image_tag("cityoflight.jpg", alt: "city of light"), 'http://en.wikipedia.org/wiki/Grinnell,_Iowa' %>
</div>	

app/views/static_pages/contact.html.erb
<div id="contact">
    <h1>abuahchu@grinnell.edu</h1>
</div>	

app/views/static_pages/cv.html.erb
<div id="welcome">
    <h1>Welcome to Lauren Flynn's Personal Website</h1>
    <p>Hi. This is a practice ROR sandbox for Chike T. Abuah</p>
    <p>Feel free to click and feel free to be</p>
</div>

app/views/static_pages/figures.html.erb
<div>
	<%= link_to image_tag("coverboy.png", alt: "coverboy"), 'https://twitter.com/thisischiik' %>
	<%= link_to image_tag("random.jpg", alt: "soccer"), 'https://twitter.com/thisischiik' %>
</div>	
	

app/views/static_pages/light_exp.html.erb
<div class="wrapper">
	<%= link_to image_tag("mac.jpg", alt: "soccer"), 'https://www.grinnell.edu/' %>
	<%= link_to image_tag("mayday.jpg", alt: "light"), 'https://www.grinnell.edu/' %>
</div>	

app/views/static_pages/light_wall.html.erb
<div class="wrapper">
	<%= link_to image_tag("morning.jpg", alt: "graduation"), 'http://new.trinity.edu/' %>
	<%= link_to image_tag("goodmorning.jpg", alt: "good morning"), 'http://new.trinity.edu/' %>
</div>	

app/views/static_pages/lines.html.erb
<div>
	<%= link_to image_tag("notaselfie.jpg", alt: "selfie"), 'http://www.linkedin.com/pub/chike-abuah/46/558/8b7' %>
	<%= link_to image_tag("alan.jpg", alt: "alan turing"), 'http://en.wikipedia.org/wiki/Alan_Turing' %>
	<%= link_to image_tag("dennis.jpg", alt: "dennis ritchie"), 'http://en.wikipedia.org/wiki/Dennis_Ritchie' %>	
</div>	

app/views/static_pages/new.html.erb
<div class="wrapper">
	<%= link_to image_tag("noyce.jpg", alt: "noyce science"), 'http://en.wikipedia.org/wiki/Robert_Noyce' %>
	<%= link_to image_tag("inb4.jpg", alt: "grinnell party"), 'http://www.grinnell.edu/campus-life/residence-life' %>
<div>	

app/views/static_pages/newer.html.erb
<div>
	<%= link_to image_tag("words.jpg", alt: "soccer"), 'http://rainymood.com/' %>
	<%= link_to image_tag("imadeup.jpg", alt: "soccer"), 'http://rainymood.com/' %>
</div>	

app/views/static_pages/sisters.html.erb
<div>
	<%= link_to image_tag("sisters.jpg", alt: "soccer"), 'http://www.youtube.com/watch?v=JCOURZ-yx4E' %>
	<%= link_to image_tag("family.jpg", alt: "soccer"), 'http://www.youtube.com/watch?v=bmXumtgwtak' %>
</div>	

app/views/static_pages/text.html.erb
<div class="wrapper">
	<%= link_to image_tag("mandela.jpg", alt: "mandela"), 'http://en.wikipedia.org/wiki/Nelson_Mandela' %>
	<%= link_to image_tag("newday.jpg", alt: "marley"), 'http://en.wikipedia.org/wiki/Bob_Marley' %>
</div>

app/views/users/home.html.erb
<div class="wrapper">
	<%= link_to image_tag("rukia.jpg", alt: "Rukia"), 'http://rainymood.com/', id: 'rukia' %>
	<%= link_to image_tag("peponi.jpg", alt: "Paradise"), 'https://github.com/chikeabuah/', id: 'paradise' %>
</div>	